In [2]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

Q2. Records count
How many records are in the dataset?

In [7]:
len(df)

10000

Q3. Fuel types
How many fuel types are presented in the dataset?

In [8]:
len(set(df.fuel_type))

3

Q4. Missing values
How many columns in the dataset have missing values?

In [ ]:
i = 0
for c in df.columns:
    if df[c].isna().any():
        i += 1
print(i)

2

Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [18]:
max(df["fuel_efficiency_mpg"])

41.2

Q6. Median value of horsepower
Find the median value of the horsepower column in the dataset.
Next, calculate the most frequent value of the same horsepower column.
Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
Now, calculate the median value of horsepower once again.

In [30]:
print(df["horsepower"].median())
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].mode())
print(df["horsepower"].median())

254.0
254.0

Q7. Sum of weights
Select all the cars from Asia
Select only columns vehicle_weight and model_year
Select the first 7 values
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?

In [35]:
df_asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [ ]:
df_asia = df[df["origin"] == "Asia"]
df_asia = df_asia[["vehicle_weight", "model_year"]]
X = np.array(df_asia[:7])
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
output = np.linalg.inv(X.T @ X) @ X.T @ y

In [45]:
np.sum(output)

np.float64(0.36919696904925486)